alias vneck='ssh albert@vneck-3.ooapi.com -L 27018:localhost:27017'
alias gloves='ssh albert@gloves.ooapi.com'
alias hoodie='ssh albert@hoodie-0.ooapi.com'
alias hoodie1='ssh albert@hoodie-1.ooapi.com'
alias pajamas='ssh albert@pajamas.ooapi.com -L 27020:localhost:27017'
alias partyhut='ssh albert@api.partyhut.hk -L 28017:localhost:27017'
